name: Build and Release Android App

on:
  repository_dispatch:
    types: [ build-app ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Log Payload
        run: |
          echo "URL: ${{ github.event.client_payload.url }}"
          echo "Package Name: ${{ github.event.client_payload.package_name }}"

      - name: Replace URL and Package Name
        run: |
          echo "Replacing URL with ${{ github.event.client_payload.url }}"
          sed "s|loadUrl(\"https://x.com/\")|loadUrl(\"${{ github.event.client_payload.url }}\")|g" wtm-android/app/src/main/java/com/prudhvir3ddy/wtm_android/MainActivity.kt
          echo "Replacing package name with ${{ github.event.client_payload.package_name }}"
          sed "s|package com.prudhvir3ddy.wtm_android|package ${{ github.event.client_payload.package_name }}|g" wtm-android/app/src/main/java/com/prudhvir3ddy/wtm_android/MainActivity.kt
          sed "s|applicationId = \"com.prudhvir3ddy.wtm_android\"|applicationId = \"${{ github.event.client_payload.package_name }}\"|g" wtm-android/app/build.gradle.kts
          sed "s|namespace = \"com.prudhvir3ddy.wtm_android\"|namespace = \"${{ github.event.client_payload.package_name }}\"|g" wtm-android/app/build.gradle.kts

      - name: Make gradlew executable
        run: chmod +x wtm-android/gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release APK
        run: |
          cd wtm-android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: wtm-android/app/build/outputs/apk/release/app-release.apk
